### ISSUE TITLE
Name & Logo

### ISSUE THREAD

**Issue by scallsen** [paprika-spice/web-app#10]

**Comment by MJholland** [comment]
Created logos.
![workspace-logo-64](https://user-images.githubusercontent.com/16650658/35710619-7d760d78-0786-11e8-845a-5ada9810485a.png)
![workspace-logo-256](https://user-images.githubusercontent.com/16650658/35710620-7dfca09a-0786-11e8-9b41-da63dcb6db6a.png)

**Comment by TeriDibbits** [comment]
Chose app name and created a logo.
