### ISSUE TITLE
Sitemap & Task Flows

### ISSUE THREAD

**Issue by scallsen** [paprika-spice/web-app#11]

**Comment by scallsen** [comment]
TASK: Complete each of the three task flows on the Week 3 project board page
--

- Home: MJ
- Room: Teri
- Supporting screens: Simon

**Comment by scallsen** [comment]
![total screens](https://user-images.githubusercontent.com/16653087/35527785-e07fb67e-04f9-11e8-90cc-4c2664837fe5.jpg)

**Comment by TeriDibbits** [comment]
Add sitemap and task flow sketches to google doc.
