### ISSUE TITLE
Testing Set up

### ISSUE THREAD

**Issue by TeriDibbits** [paprika-spice/web-app#20]

**Comment by TeriDibbits** [comment]
Testing objectives:
The objective is to identify issues in the task flows and determine if the purpose of the app is understood.

Determine flows & scenarios:
Task #1: Login and select a time and date you wish to book a room
Task #2: Select the building you wish to book a room in
Task #3: Select the features you wish to see in the room you are booking
Task #4: Book a room

Identify devices:
We are going to use a phone connected to the laptop displaying the live XD file prototype. No sound required.

**Comment by scallsen** [comment]
**Name:** Kelly Miles
**Facilitator observations:** Was able to book and reserve a room with no issues
**Participant feedback:** The Adobe XD interface made it difficult to tap certain items, no issues with the app

**Comment by scallsen** [comment]
@MJholland @TeriDibbits We need a total of five users to test, please run them through and post here. We will then compile into one document to show Thomas

**Comment by MJholland** [comment]
@scallsen We can pick anyone to do testing with right?

**Comment by TeriDibbits** [comment]
Testing set up complete
