### ISSUE TITLE
Create the two rubrics

### ISSUE THREAD

**Issue by scallsen** [paprika-spice/web-app#3]
https://learn-the-web.algonquindesign.ca/courses/web-dev-6/week-02/#success-criteria-definitions

**Comment by scallsen** [comment]
[Google Sheets](https://docs.google.com/spreadsheets/d/1OPnJfpnk5cI03bufGIFhfX8X0S56niz9LhT0uIRXqvE/edit?usp=sharing)

**Comment by MJholland** [comment]
## DESIGN & RESEARCH COMPONENT

| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Utilization of Github tools each week** | Did not use Github tools | Sometimes used Github tools | Used Github tools every week somewhat correctly for most tasks | Used Github tools every week correctly for all tasks |
| **Target Audience** | There was no defined target audience defined | The target audience defined somewhat matched the product's goals | The target audience mostly matched the product's goals | The target audience correctly matches the product's goals |
| **Competitive Analysis** | No research was done for competitors | Very little research was done for competitors | Some research was done, and some used in the conceptual development phase | Competitors were researched and considered in the conceptual development phase |
| **North Star - End Goal** | The end goal was not considered, and the application either solved another goal entirely or accomplished nothing at all. | The end product met a few of the goals defined in the development phase | The end product met most of the goals defined in the development phase | The end product met all the goals defined in the conceptual development phase |
| **External Feedback** | There was no user testing performed | 1 or 2 external sources were interviewed/used in user testing | 3 or 4 external sources were interviewed/used in user testing | At least 5 or more external sources were interviewed/used in user testing |
| **Teamwork** | What team? | Some teamwork happened but it fell apart after a short time.  | Communication was something, work was performed ok together | Worked great together. Communicated often and made decisions together. Everyone took on the workload they were assigned. |
| **Quality of wireframes** | Wireframes were not present / such low quality they are unusable | Wireframes were rough and not useful for further development | Wireframes were mostly complete and somewhat organized; usable for further development  | Wireframes are effective, clean, and communicate the website's goals. |
| **Quality of prototype ** | Prototype is poorly executed and incomplete | Prototype is somewhat organized and complete | Prototype is mostly organized and complete | Prototype looks cohesive, organized, and includes enough detail |

**Comment by MJholland** [comment]
## DATA & CODING COMPONENT

| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Accessibility** | No one can use the site | Only accessible to a handful of special people | Accessible to most people | Anyone in the world can use the site |
| **Responsiveness** | Not responsive | Responsive on some screens | Responsive but there is some issues | Website is responsive and looks great on all screen sizes |
| **Performance** | Doesn't load or loads super slow | Loads slowly | Good loading time, but could be faster | Excellent loading time |
| **Code Quality** | Coded by someone in Kindergarten | Code quality of a first year student | Coded like a second year, close to perfect but still lacking | Semantically correct and fully incorporates best practices |
| **Teamwork** | What team? | Some teamwork happened but it fell apart after a short time.  | Communication was something, work was performed ok together | Worked great together. Communicated often and made decisions together. Everyone took on the workload they were assigned. |

**Comment by TeriDibbits** [comment]
Two rubrics were completed.
