### ISSUE TITLE
Jekyll-ify the default look

### ISSUE THREAD

**Issue by MJholland** [paprika-spice/web-app#34]
All the info about how to do this is [here](https://learn-the-web.algonquindesign.ca/courses/web-dev-5/week-06/)
Blocked for now until @scallsen finishes with sketching.
This may carry over to the next sprint.

**Comment by scallsen** [comment]
Sketching done, we can now work on this.
![new sketch](https://user-images.githubusercontent.com/16653087/36685271-d2f26a12-1af0-11e8-81d6-beb1d9a2a992.jpg)
