### ISSUE TITLE
Update project description

### ISSUE THREAD

**Issue by scallsen** [paprika-spice/web-app#4]

**Comment by MJholland** [comment]
I was thinking it should read something like this:

> This repository is a prototype for a web app. 
> [APP NAME] is a room/workspace booking app for school campuses.
> This has been created in Algonquin College's Graphic Design Web Dev 6 course.

And once we have a logo we can swap out the paprika for it.

**Comment by scallsen** [comment]
This repository is a prototype for a web app.
Workspace is a room/workspace booking app for school campuses.
This has been created in Algonquin College's Graphic Design Web Dev 6 course.
