### ISSUE TITLE
Usability Testing

### ISSUE THREAD

**Issue by TeriDibbits** [paprika-spice/web-app#57]

**Comment by TeriDibbits** [comment]
Usability Testing link:
https://learn-the-web.algonquindesign.ca/courses/shared/usability-testing/ 
Checklist:
https://learn-the-web.algonquindesign.ca/topics/usability-testing-checklist/

**Comment by scallsen** [comment]
## Usability Testing

No issues found with flow in user testing. 

Only issue: Safari for MacOS does not support the date picker.
