### ISSUE TITLE
Potential app flows and features

### ISSUE THREAD

**Issue by TeriDibbits** [paprika-spice/web-app#6]
Develop potential app flows and features of the app

**Comment by TeriDibbits** [comment]
![paprika-teri-app-flows-features-01](https://user-images.githubusercontent.com/16690597/35486584-fa0527bc-043d-11e8-93a7-9b4ce59cc2dc.jpg)
![paprika-teri-app-flows-features-02](https://user-images.githubusercontent.com/16690597/35486585-fa131dfe-043d-11e8-874c-7e49fe3a1f49.jpg)

**Comment by scallsen** [comment]
![flow and screens - simon](https://user-images.githubusercontent.com/16653087/35524395-7fe1840a-04ef-11e8-939b-e0596824514d.jpg)

**Comment by scallsen** [comment]
Completed discussion in class.
