### ISSUE TITLE
Accessibility Testing

### ISSUE THREAD

**Issue by TeriDibbits** [paprika-spice/web-app#76]

**Comment by TeriDibbits** [comment]
Accessibility Testing link:
https://learn-the-web.algonquindesign.ca/courses/shared/accessibility-testing/ 
Checklist:
https://learn-the-web.algonquindesign.ca/topics/accessibility-testing-checklist/

**Comment by TeriDibbits** [comment]
Accessibility testing completed.
Tested skip links, voiceover, colour, alt attributes, ARIA implementation, and heading structure. Suggested tools from the checklist were used to complete testing.

**Comment by scallsen** [comment]
## Web Developer Toolbar Features Test
**No images** Accessible, text descriptions are available.
**No CSS** Accessible, correct hierarchy is used. 
**No JavaScript** No JS used.
**No sound** No sound used. 
**No mouse (AKA keyboard access)** Skip links functional.

**Comment by TeriDibbits** [comment]
Areas to improvements:
Colour contrast between room buttons could be improved. The 3 second delay to home page after successfully booking or cancelling button would need some altering so it doesn't cause confusion when using voice over. The user isn't aware that the page will refresh in 3 seconds.

**Comment by TeriDibbits** [comment]
Accessiblity testing completed.
