### ISSUE TITLE
Browser Testing

### ISSUE THREAD

**Issue by TeriDibbits** [paprika-spice/web-app#77]

**Comment by TeriDibbits** [comment]
Browser testing link:
https://learn-the-web.algonquindesign.ca/courses/shared/browser-testing/ 
Checklist:
https://learn-the-web.algonquindesign.ca/topics/browser-testing-checklist/

**Comment by scallsen** [comment]
## Mobile Testing
Google Pixel XL
Android 8.1.0

**Chrome** No issues
**Opera Mini** No issues
**Opera** No issues
**Firefox** No issues
**Microsoft Edge** No issues

**Comment by MJholland** [comment]
## Desktop Testing

**Chrome:** no issues
**Opera:** no issues
**Firefox:** no issues
**Safari:** Turns type:"date" field into a type:"text" field
