### ISSUE TITLE
Visual Design

### ISSUE THREAD

**Issue by scallsen** [paprika-spice/web-app#9]

**Comment by scallsen** [comment]
Keeping our application appearance should be simple, with opportunity for clients to brand them to the specific school's look and feel (e.g. colour).

I really am a fan of using Bootstrap's basic look and feel: 
https://getbootstrap.com/docs/4.0/examples/

**Comment by scallsen** [comment]
TASK: Research different prototyping options for coding our final result
--
Options:
- Bootstrap
- Foundation
- Learn the Web + Customization

**Comment by scallsen** [comment]
TASK: Find an appropriate web font to use in the application
--
Options:

- Lato
- Josefin Sans
- Rubik

**Comment by TeriDibbits** [comment]
Invision board link:
https://projects.invisionapp.com/boards/KE3I1ZZVF4B/

**Comment by TeriDibbits** [comment]
Visual Design was discussed and developed on an invision board.
